version: '3.8'
name: beatbuddy
services:
  pg:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=beatbuddy
      - POSTGRES_USER=beatbuddy
      - POSTGRES_PASSWORD=beatbuddy
    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - default
networks:
  default:
    name: beatbuddy
    driver: bridge
