server:
  port: 8000
spring:
  application:
    name: beatbuddy-api
  jpa:
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.beatbuddy.io.vn/realms/beatbuddy/protocol/openid-connect/certs
  devtools:
    add-properties: false
    livereload:
      enabled: false
  docker:
    compose:
      enabled: false
springdoc:
  api-docs:
    path: /apidocs
  swagger-ui:
    path: /apidocs.html
    oauth2RedirectUrl: https://api.beatbuddy.io.vn/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: web
      use-pkce-with-authorization-code-grant: true

logging:
  level:
    root: INFO
    "[vn.io.vutiendat3601.beatbuddy]": DEBUG
client:
  auth:
    url: http://localhost:8000

auth:
  client:
    keycloak:
      resource-management:
        authServerUrl: https://auth.beatbuddy.io.vn
        realm: beatbuddy
        clientId: resource-management
        clientSecret: JqMYJcGpELv8g93dGGBChjzcaWZbWtGf
        permissions:
      user-management:
        authServerUrl: https://auth.beatbuddy.io.vn
        realm: beatbuddy
        clientId: user-management
        clientSecret: oH6fyIexWj8OrRp9d8LPdyDgTtXc1Tb6
      web-representation:
        authServerUrl: https://auth.beatbuddy.io.vn
        realm: beatbuddy
        clientId: web-representation
        clientSecret: 9zhHRYgodGe6bhTZqai8qXigNQQXkkCY
  resource:
    urn:
      numberOfParts: 3
      typePartIndex: 1
      idPartIndex: 2
      partSeparator: ":"
    types:
      - name: playlist
        uriPrefixes: ["/v1/playlists/{id}", "/v1/playlists/{id}/add-item"]
        ownerScopes:
          [playlist:permission, playlist:view, playlist:edit, playlist:delete]
        requesterScopes: [playlist:permission, playlist:view, playlist:edit]

security:
  routeSpecs:
    # Auth
    - uris: /v1/auth/users,/v1/auth/users/{id}
      method: GET
      authorities: user:view

    # Catalog
    - uris: /v1/catalog/feed/*
      method: GET
      authorities: catalog:feed
    - uris: /v1/catalog/search
      method: GET
      authorities: catalog:search

    # User
    - uris: /v1/users,/v1/users/{id},/v1/auth/users,/v1/auth/users/{id}
      method: GET
      authorities: user:view

    # Track
    - uris: /v1/tracks,/v1/tracks/{id}
      method: GET
      authorities: track:view

    # Artist
    - uris: /v1/artists,/v1/artists/{id},/v1/artists/{id}/popular-tracks
      method: GET
      authorities: artist:view

    # Playlist
    - uris: /v1/playlists
      method: POST
      authorities: playlist:create
    - uris: /v1/playlists/{id}
      method: GET
      authorities: playlist:view
    - uris: /v1/playlists/{id},/v1/playlists/{id}/add-item
      method: PUT
      authorities: playlist:edit
    - uris: /v1/playlists/{id}/items
      method: DELETE
      authorities: playlist:edit
    - uris: /v1/playlists/{id}/permissions/grant
      method: POST
      authorities: playlist:permission
    - uris: /v1/playlists/{id}/permissions/revoke
      method: DELETE
      authorities: playlist:permission

    # TrackSuggestion
    - uris: /v1/catalog/track-suggestions
      method: POST
      authorities: track-suggestion:create
    - uris: /v1/catalog/track-suggestions/{id}
      method: GET
      authorities: track-suggestion:view
    - uris: /v1/catalog/track-suggestions/{id}
      method: UPDATE
      authorities: track-suggestion:edit
    - uris: /v1/catalog/track-suggestions/{id}
      method: DELETE
      authorities: track-suggestion:delete

    # File
    - uris: /v1/audio/files,/v1/audio/files/{id}
      method: GET
      authorities: audio:view-file
# amazon:
#   s3:
#     accessKey: DO00JPHVYHZDQELCZL7B
#     secretKey: yD7dcot8HPooLe1rYAmbV+5X95M7s5fPaZm/3GOTTfw
#     region: ""
#     serviceEndpoint: sgp1.digitaloceanspaces.com
#     bucketName: beatbuddyaudio
#     cdnBaseUrls:
#       - https://beatbuddyaudio.sgp1.digitaloceanspaces.com
